#!/usr/bin/env python3
"""Pack Megatect artifacts into a compact canonical architecture context."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

SKIP_DIRS = {".git", ".hg", ".next", ".turbo", ".venv", "__pycache__", "build", "coverage", "dist", "node_modules", "target", "venv"}
HASH_SUFFIXES = {".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".go", ".rs", ".java", ".kt", ".rb", ".php", ".cs", ".swift", ".toml", ".json", ".yaml", ".yml", ".sql", ".prisma"}


def read_json(path: str | Path | None) -> dict:
    if not path:
        return {}
    p = Path(path)
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else {}


def git_value(root: Path, args: list[str]) -> str:
    try:
        return subprocess.check_output(["git", "-C", str(root), *args], text=True, stderr=subprocess.DEVNULL).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def iter_hash_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        try:
            parts = path.relative_to(root).parts
        except ValueError:
            continue
        if any(part in SKIP_DIRS for part in parts):
            continue
        if path.suffix in HASH_SUFFIXES or path.name in {"Dockerfile", "Makefile"}:
            files.append(path)
    return sorted(files)


def source_files_hash(root: Path) -> str:
    digest = hashlib.sha256()
    for path in iter_hash_files(root):
        digest.update(rel(path, root).encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def file_hash(path: str | Path | None) -> str | None:
    if not path:
        return None
    p = Path(path)
    if not p.exists():
        return None
    return hashlib.sha256(p.read_bytes()).hexdigest()


def first(items: list, limit: int) -> list:
    return list(items or [])[:limit]


def artifact_hashes(paths: dict[str, str | None]) -> dict[str, str]:
    hashes = {}
    for name, path in paths.items():
        value = file_hash(path)
        if value:
            hashes[name] = value
    return hashes


def infer_repo_root(inventory: dict, index: dict, fallback: Path) -> Path:
    for data in (inventory, index):
        value = data.get("root")
        if value:
            return Path(str(value)).resolve()
    return fallback.resolve()


def markdown(repo: Path, inventory: dict, index: dict, scorecard: dict, boundary: dict, pattern_fit: dict, manifest: dict) -> str:
    systems = index.get("systems", {})
    system_edges = index.get("system_edges", [])
    hubs = index.get("top_hubs", {})
    patterns = pattern_fit.get("patterns", {})
    violations = boundary.get("violations", []) if isinstance(boundary, dict) else []
    lines = [
        "# Canonical Architecture Context",
        "",
        "This file is generated by Megatect. Read it before broad repo discovery, then inspect only the files needed to confirm current drift.",
        "",
        "## Provenance",
        "",
        f"- Repo: `{repo}`",
        f"- Branch: `{manifest['generated_branch']}`",
        f"- Commit: `{manifest['generated_commit']}`",
        f"- Commit time: `{manifest['generated_at']}`",
        f"- Source hash: `{manifest['source_files_hash']}`",
        "",
        "## Repo Shape",
        "",
        f"- Files inventoried: {inventory.get('files', index.get('files', 0))}",
        f"- Stacks: {', '.join(inventory.get('stacks', [])) or 'unknown'}",
        f"- Systems: {len(systems)}",
        f"- File edges: {index.get('file_edges', len(index.get('edges', [])))}",
        f"- Cycles: {len(index.get('cycles', []))}",
        f"- Risk tier: {scorecard.get('risk_tier', 'unknown')}",
        "",
        "## Entry Points And Integration Surfaces",
        "",
    ]
    for label, key, limit in [
        ("Entrypoints", "entrypoints", 30),
        ("API routes", "api_routes", 40),
        ("Workers/jobs", "workers", 30),
        ("Schemas/models", "schemas", 30),
        ("Configs", "configs", 30),
    ]:
        values = first(inventory.get(key, []), limit)
        lines.append(f"- {label}: {', '.join(f'`{v}`' for v in values) if values else 'none detected'}")
    lines.append(f"- Integrations: {', '.join(inventory.get('integrations', [])) or 'none detected'}")
    lines.extend(["", "## Systems", ""])
    if systems:
        for name, files in sorted(systems.items()):
            examples = ", ".join(f"`{v}`" for v in first(files, 8))
            suffix = f" ({max(len(files) - 8, 0)} more)" if len(files) > 8 else ""
            lines.append(f"- `{name}`: {len(files)} files" + (f"; {examples}{suffix}" if examples else ""))
    else:
        lines.append("- No systems detected.")
    lines.extend(["", "## Dependency Graph Summary", ""])
    if system_edges:
        lines.extend(f"- `{src}` -> `{dst}`" for src, dst in first(system_edges, 80))
    else:
        lines.append("- No cross-system edges detected.")
    lines.extend(["", "## Hotspots", ""])
    incoming = hubs.get("incoming", []) if isinstance(hubs, dict) else []
    outgoing = hubs.get("outgoing", []) if isinstance(hubs, dict) else []
    lines.append("- High incoming: " + (", ".join(f"`{h.get('node')}` ({h.get('count')})" for h in first(incoming, 10)) or "none"))
    lines.append("- High outgoing: " + (", ".join(f"`{h.get('node')}` ({h.get('count')})" for h in first(outgoing, 10)) or "none"))
    lines.extend(["", "## Boundaries And Risks", ""])
    if violations:
        lines.extend(f"- {v.get('type', 'violation')}: `{v.get('src', '')}` -> `{v.get('dst', '')}`" for v in first(violations, 30))
    else:
        lines.append("- No boundary violations reported by the generated graph check.")
    for rec in scorecard.get("recommendations", []):
        lines.append(f"- {rec}")
    lines.extend(["", "## Pattern Fit", ""])
    if patterns:
        for name, info in sorted(patterns.items()):
            lines.append(f"- `{name}`: {info.get('fit', 'unknown')} - {info.get('reason', '')}")
    else:
        lines.append("- No pattern-fit artifact supplied.")
    lines.extend(["", "## Agent Routing Rule", ""])
    lines.append("- For architecture, repo-wide debugging, and large refactors: run `architecture_context_check.py` first.")
    lines.append("- If freshness is `fresh` or `usable-with-drift`, use this file as the repo baseline and inspect only changed or task-specific files.")
    lines.append("- If freshness is `needs-light-refresh`, refresh the context pack when cheap; otherwise read this file plus changed entrypoint/config files.")
    lines.append("- If freshness is `needs-full-refresh`, regenerate Megatect artifacts before relying on this file.")
    return "\n".join(lines) + "\n"


def build(args: argparse.Namespace) -> tuple[str, dict]:
    inventory = read_json(args.inventory)
    index = read_json(args.index)
    scorecard = read_json(args.scorecard)
    boundary = read_json(args.boundary)
    pattern_fit = read_json(args.pattern_fit)
    repo = infer_repo_root(inventory, index, Path(args.repo or "."))
    skill_root = Path(__file__).resolve().parents[1]
    artifact_paths = {
        "inventory": args.inventory,
        "index": args.index,
        "scorecard": args.scorecard,
        "boundary": args.boundary,
        "pattern_fit": args.pattern_fit,
    }
    commit = git_value(repo, ["rev-parse", "HEAD"])
    manifest = {
        "schema_version": 1,
        "generated_at": git_value(repo, ["show", "-s", "--format=%cI", "HEAD"]) if commit != "unknown" else "unknown",
        "generated_commit": commit,
        "generated_branch": git_value(repo, ["branch", "--show-current"]),
        "repo_root": str(repo),
        "source_files_hash": source_files_hash(repo),
        "megatect_version": git_value(skill_root, ["rev-parse", "HEAD"]),
        "artifact_hashes": artifact_hashes(artifact_paths),
    }
    return markdown(repo, inventory, index, scorecard, boundary, pattern_fit, manifest), manifest


def self_test() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / "src/systems/a").mkdir(parents=True)
        (root / "src/systems/a/index.ts").write_text("export const a = 1;\n", encoding="utf-8")
        inventory = {"root": str(root), "files": 1, "stacks": ["node"], "entrypoints": ["src/systems/a/index.ts"], "integrations": []}
        index = {"root": str(root), "files": 1, "file_edges": 0, "systems": {"a": ["src/systems/a/index.ts"]}, "system_edges": [], "edges": [], "cycles": [], "top_hubs": {"incoming": [], "outgoing": []}}
        scorecard = {"risk_tier": "low", "recommendations": ["Preserve simple boundaries."]}
        paths = {}
        for name, data in {"inventory": inventory, "index": index, "scorecard": scorecard}.items():
            p = root / f"{name}.json"
            p.write_text(json.dumps(data), encoding="utf-8")
            paths[name] = p
        ns = argparse.Namespace(repo=str(root), inventory=str(paths["inventory"]), index=str(paths["index"]), scorecard=str(paths["scorecard"]), boundary=None, pattern_fit=None)
        text1, manifest1 = build(ns)
        text2, manifest2 = build(ns)
        assert text1 == text2
        assert manifest1 == manifest2
        assert "Canonical Architecture Context" in text1
        assert manifest1["source_files_hash"]


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".")
    parser.add_argument("--inventory", default="docs/architecture/inventory.json")
    parser.add_argument("--index", default="docs/architecture-graphs/architecture-index.json")
    parser.add_argument("--scorecard", default="docs/architecture/scorecard.json")
    parser.add_argument("--boundary", default="docs/architecture/boundary-report.json")
    parser.add_argument("--pattern-fit", default="docs/architecture/pattern-fit.json")
    parser.add_argument("--out", default="docs/architecture/CONTEXT.md")
    parser.add_argument("--manifest", default="docs/architecture/context-manifest.json")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv)
    if args.self_test:
        self_test()
        print("architecture_context_pack self-test passed")
        return 0
    repo = Path(args.repo).resolve()
    for attr in ("inventory", "index", "scorecard", "boundary", "pattern_fit", "out", "manifest"):
        value = getattr(args, attr)
        if value and not Path(value).is_absolute():
            setattr(args, attr, str(repo / value))
    text, manifest = build(args)
    out = Path(args.out)
    manifest_out = Path(args.manifest)
    out.parent.mkdir(parents=True, exist_ok=True)
    manifest_out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    manifest_out.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {out} and {manifest_out}: commit={manifest['generated_commit'][:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
